### ISSUE TITLE
Milestone with selected Issues for community to help with

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#368]
- [x] use relevant label(s) (include size)
- [x] move relevant issues over to this milestone 
- [x] order milestone in priority order (if possible)
- [x] add link to README for community milestone

**Comment by lorenaqendro** [comment]
- [x] Create milestone with labeled issues
- [ ] Go through the current issues and see which one should go in the milestone

**Comment by lorenaqendro** [comment]
This issue can be closed as we've created the milestone and added issues to them.
This is a continuous task we'll be continue doing as the issues arise.
